// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAztf1zxKYLdW16yCe2DHMdvlCrWaD0Jbg',
    appId: '1:614970787893:web:46a0a0922b0dac6fa7497c',
    messagingSenderId: '614970787893',
    projectId: 'flutter-firebase-first-dbf14',
    authDomain: 'flutter-firebase-first-dbf14.firebaseapp.com',
    storageBucket: 'flutter-firebase-first-dbf14.firebasestorage.app',
    measurementId: 'G-KYY3R2942V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtbr5zajV9nOYd5pRIGGYQl0kgOfsI87k',
    appId: '1:614970787893:android:f01a8ef106a42a3fa7497c',
    messagingSenderId: '614970787893',
    projectId: 'flutter-firebase-first-dbf14',
    storageBucket: 'flutter-firebase-first-dbf14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGLqjCvggVnInFqD_KunLUbjGo1-83ROA',
    appId: '1:614970787893:ios:565673caf70dce6da7497c',
    messagingSenderId: '614970787893',
    projectId: 'flutter-firebase-first-dbf14',
    storageBucket: 'flutter-firebase-first-dbf14.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGLqjCvggVnInFqD_KunLUbjGo1-83ROA',
    appId: '1:614970787893:ios:565673caf70dce6da7497c',
    messagingSenderId: '614970787893',
    projectId: 'flutter-firebase-first-dbf14',
    storageBucket: 'flutter-firebase-first-dbf14.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAztf1zxKYLdW16yCe2DHMdvlCrWaD0Jbg',
    appId: '1:614970787893:web:8e39044b9b9a24c3a7497c',
    messagingSenderId: '614970787893',
    projectId: 'flutter-firebase-first-dbf14',
    authDomain: 'flutter-firebase-first-dbf14.firebaseapp.com',
    storageBucket: 'flutter-firebase-first-dbf14.firebasestorage.app',
    measurementId: 'G-9JGLDNQZC8',
  );

}